plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\dongmin ai company\\landing-pages\\summer-camp"
publishOrigin = "default"
base = "D:\\dongmin ai company\\landing-pages\\summer-camp"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]